class FindingsController < ApplicationController

  hobo_model_controller

  auto_actions :all, :except => :index

  auto_actions_for :estd311, :create
  auto_actions_for :estd312, :create
  auto_actions_for :estd321, :create
  auto_actions_for :estd322, :create
  auto_actions_for :estd331, :create
  auto_actions_for :estd332, :create
  auto_actions_for :estd411, :create
  auto_actions_for :estd412, :create
  auto_actions_for :estd421, :create
  auto_actions_for :estd422, :create
  auto_actions_for :estd431, :create
  auto_actions_for :estd432, :create
  auto_actions_for :estd441, :create
  auto_actions_for :estd442, :create
  auto_actions_for :estd443, :create
  auto_actions_for :estd444, :create
  auto_actions_for :estd445, :create
  auto_actions_for :estd451, :create
  auto_actions_for :estd452, :create
  auto_actions_for :estd453, :create
  auto_actions_for :estd461, :create
  auto_actions_for :estd4621, :create
  auto_actions_for :estd4622, :create
  auto_actions_for :estd4623, :create
  auto_actions_for :estd4624, :create
  auto_actions_for :estd4625, :create
  auto_actions_for :estd4626, :create
  auto_actions_for :estd4627, :create
  auto_actions_for :estd4631, :create
  auto_actions_for :estd4632, :create
  auto_actions_for :estd4633, :create
  auto_actions_for :estd4634, :create
  auto_actions_for :estd4635, :create
  auto_actions_for :estd4636, :create
  auto_actions_for :estd4637, :create
  auto_actions_for :estd4638, :create
  auto_actions_for :estd4639, :create
  auto_actions_for :estd46310, :create
  auto_actions_for :estd46311, :create
  auto_actions_for :estd46312, :create
  auto_actions_for :estd46313, :create
  auto_actions_for :estd46314, :create
  auto_actions_for :estd46315, :create
  auto_actions_for :estd46316, :create
  auto_actions_for :estd46317, :create
  auto_actions_for :estd46318, :create
  auto_actions_for :estd46319, :create
  auto_actions_for :estd46320, :create
  auto_actions_for :estd46321, :create
  auto_actions_for :estd46322, :create
  auto_actions_for :estd46323, :create
  auto_actions_for :estd46324, :create
  auto_actions_for :estd46325, :create
  auto_actions_for :estd46326, :create
  auto_actions_for :estd46327, :create
  auto_actions_for :estd46328, :create
  auto_actions_for :estd46329, :create
  auto_actions_for :estd464, :create
  auto_actions_for :estd465, :create
  auto_actions_for :estd466, :create
  auto_actions_for :estd471, :create
  auto_actions_for :estd472, :create
  auto_actions_for :estd473, :create
  auto_actions_for :estd474, :create
  auto_actions_for :estd475, :create
  auto_actions_for :estd481, :create
  auto_actions_for :estd482, :create
  auto_actions_for :estd483, :create
  auto_actions_for :estd4841, :create
  auto_actions_for :estd4842, :create
  auto_actions_for :estd4843, :create
  auto_actions_for :estd485, :create
  auto_actions_for :estd486, :create
  auto_actions_for :estd491, :create
  auto_actions_for :estd492, :create
  auto_actions_for :estd4101, :create
  auto_actions_for :estd4102, :create
  auto_actions_for :estd4103, :create
  auto_actions_for :estd4104, :create
  auto_actions_for :estd4105, :create
  auto_actions_for :estd4106, :create
  auto_actions_for :estd4107, :create
  auto_actions_for :estd4111, :create
  auto_actions_for :estd4112, :create
  auto_actions_for :estd4113, :create
  auto_actions_for :estd4114, :create
  auto_actions_for :estd4121, :create
  auto_actions_for :estd4122, :create
  auto_actions_for :estd4131, :create
  auto_actions_for :estd4132, :create
  auto_actions_for :estd4133, :create
  auto_actions_for :estd4134, :create
  auto_actions_for :estd4141, :create
  auto_actions_for :estd4142, :create
  auto_actions_for :estd4143, :create
  auto_actions_for :estd4151, :create
  auto_actions_for :estd41521, :create
  auto_actions_for :estd41522, :create
  auto_actions_for :estd41523, :create
  auto_actions_for :estd41524, :create
  auto_actions_for :estd41525, :create
  auto_actions_for :estd4153, :create
  auto_actions_for :estd4154, :create
  auto_actions_for :estd4155, :create
  auto_actions_for :mil111, :create
  auto_actions_for :mil112, :create
  auto_actions_for :mil121, :create
  auto_actions_for :mil131, :create
  auto_actions_for :mil141, :create
  auto_actions_for :mil211, :create
  auto_actions_for :mil212, :create
  auto_actions_for :mil221, :create
  auto_actions_for :mil222, :create
  auto_actions_for :mil231, :create
  auto_actions_for :mil311, :create
  auto_actions_for :mil321, :create
  auto_actions_for :mil331, :create
  auto_actions_for :mil341, :create
  auto_actions_for :mil351, :create
  auto_actions_for :mil361, :create
  auto_actions_for :mil371, :create
  auto_actions_for :mil381, :create
  auto_actions_for :mil391, :create
  auto_actions_for :mil411, :create
  auto_actions_for :mil412, :create
  auto_actions_for :mil413, :create
  auto_actions_for :mil421, :create
  auto_actions_for :mil431, :create
  auto_actions_for :mil432, :create
  auto_actions_for :mil441, :create
  auto_actions_for :mil442, :create
  auto_actions_for :mil451, :create
  auto_actions_for :mil452, :create
  auto_actions_for :mil453, :create
  auto_actions_for :mil461, :create
  auto_actions_for :mil462, :create
  auto_actions_for :mil463, :create
  auto_actions_for :mil464, :create
  auto_actions_for :mil465, :create
  auto_actions_for :mil511, :create
  auto_actions_for :mil512, :create
  auto_actions_for :mil513, :create
  auto_actions_for :mil521, :create
  auto_actions_for :mil522, :create
  auto_actions_for :mil531, :create
  auto_actions_for :mil532, :create
  auto_actions_for :mil533, :create
  auto_actions_for :mil534, :create
  auto_actions_for :mil535, :create
  auto_actions_for :mil536, :create
  auto_actions_for :mil537, :create
  auto_actions_for :mil538, :create
  auto_actions_for :mil611, :create
  auto_actions_for :mil621, :create
  auto_actions_for :mil711, :create
  auto_actions_for :mil712, :create
  auto_actions_for :mil713, :create
  auto_actions_for :mil714, :create
  auto_actions_for :mil721, :create
  auto_actions_for :mil722, :create
  auto_actions_for :mil723, :create
  auto_actions_for :mil724, :create
  auto_actions_for :mil725, :create
  auto_actions_for :mil731, :create
  auto_actions_for :mil741, :create
  auto_actions_for :mil751, :create
  auto_actions_for :mil3101, :create
  auto_actions_for :mil3102, :create
  auto_actions_for :mil3103, :create
  auto_actions_for :med11, :create
  auto_actions_for :med12, :create
  auto_actions_for :med21, :create
  auto_actions_for :med22, :create
  auto_actions_for :med23, :create
  auto_actions_for :med24, :create
  auto_actions_for :med25, :create
  auto_actions_for :med26, :create
  auto_actions_for :med27, :create
  auto_actions_for :med28, :create
  auto_actions_for :med31, :create
  auto_actions_for :med32, :create
  auto_actions_for :med33, :create
  auto_actions_for :med41, :create
  auto_actions_for :med42, :create
  auto_actions_for :med43, :create
  auto_actions_for :med44, :create
  auto_actions_for :med45, :create
  auto_actions_for :med51, :create
  auto_actions_for :med52, :create
  auto_actions_for :med53, :create
  auto_actions_for :med54, :create
  auto_actions_for :med55, :create
  auto_actions_for :med56, :create
  auto_actions_for :med61, :create
  auto_actions_for :med62, :create
  auto_actions_for :med71, :create
  auto_actions_for :med81, :create
  auto_actions_for :med91, :create
  auto_actions_for :med92, :create
  auto_actions_for :med93, :create
  auto_actions_for :med94, :create
  auto_actions_for :med101, :create
  auto_actions_for :med102, :create
  auto_actions_for :med111, :create
  auto_actions_for :med112, :create

end
